"use client";

import {useEffect, useState} from "react";
import {useRouter, useSearchParams} from "next/navigation";
import {api} from "@/lib/api";
import {useI18n} from "@/lib/i18n";
import {Brand} from "./Brand";
import {Modal} from "./Modal";
import {AuthPanel} from "./AuthPanel";
import {LocaleSelect} from "./LocaleSelect";

export function Portal(){
  const {t}=useI18n(); const router=useRouter(); const params=useSearchParams();
  const [authMode,setAuthMode]=useState<"login"|"register"|null>(params.get("auth") as "login"|"register"|null); const [contactOpen,setContactOpen]=useState(false);
  useEffect(()=>{const pay=params.get("pay");const action=params.get("action");const token=params.get("token");if(pay){router.replace(`/payment/?token=${encodeURIComponent(pay)}`);return}if(action&&token){router.replace(`/action/?action=${encodeURIComponent(action)}&token=${encodeURIComponent(token)}`);return}api.restore().then(user=>{if(user)router.replace("/app/")}).catch(()=>{})},[params,router]);
  function scroll(id:string){document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"})}
  return <div className="page-bg">
    <header className="topbar"><Brand compact/><nav className="top-actions portal-nav"><button className="button ghost" onClick={()=>scroll("features")}>{t("portalNavFeatures")}</button><button className="button ghost" onClick={()=>scroll("how")}>{t("portalNavHowItWorks")}</button><button className="button ghost" onClick={()=>setContactOpen(true)}>{t("portalNavContact")}</button></nav><div className="top-actions"><LocaleSelect/><button className="button secondary" onClick={()=>setAuthMode("login")}>{t("login")}</button><button className="button" onClick={()=>setAuthMode("register")}>{t("register")}</button></div></header>
    <main className="container">
      <section className="hero"><div><span className="eyebrow">{t("portalHeroEyebrow")}</span><h1>{t("headline")}</h1><p>{t("subtitle")}</p><div className="hero-actions"><button className="button" onClick={()=>setAuthMode("register")}>{t("register")}</button><button className="button secondary" onClick={()=>scroll("how")}>{t("portalNavHowItWorks")}</button></div></div><div className="portal-visual"><h3>{t("recentCollections")}</h3>{[["portalDemoTrip",18,22],["portalDemoClub",31,34],["portalDemoCourse",12,12]].map(([key,p,tTotal])=><div className="mini-row" key={String(key)}><div><strong>{t(String(key))}</strong><div className="progress"><span style={{width:`${Number(p)/Number(tTotal)*100}%`}}/></div></div><strong>{p}/{tTotal}</strong></div>)}</div></section>
      <section className="section"><div className="cards"><div className="card"><h3>{t("portalTrustDirect")}</h3></div><div className="card"><h3>{t("portalTrustFlexible")}</h3></div><div className="card"><h3>{t("portalTrustMultilingual")}</h3></div></div></section>
      <section className="section" id="features"><h2>{t("portalNavFeatures")}</h2><p className="section-intro">{t("portalFeaturesIntro")}</p><div className="cards"><div className="card"><h3>{t("participantLists")}</h3><p className="muted">{t("participantContactHint")}</p></div><div className="card"><h3>{t("collections")}</h3><p className="muted">{t("paymentLink")}</p></div><div className="card"><h3>{t("bankStatementImport")}</h3><p className="muted">{t("bankImportHint")}</p></div><div className="card"><h3>{t("messageTemplates")}</h3><p className="muted">{t("sameMessageAllChannels")}</p></div><div className="card"><h3>{t("onlinePayments")}</h3><p className="muted">{t("onlinePaymentsHint")}</p></div><div className="card"><h3>{t("apiIntegrations")}</h3><p className="muted">{t("apiAccessHint")}</p></div></div></section>
      <section className="section" id="how"><h2>{t("portalNavHowItWorks")}</h2><p className="section-intro">{t("portalHowIntro")}</p><div className="cards">{[[1,"portalStepOneTitle","portalStepOneBody"],[2,"portalStepTwoTitle","portalStepTwoBody"],[3,"portalStepThreeTitle","portalStepThreeBody"]].map(([n,title,body])=><div className="card" key={String(n)}><div className="step-number">{n}</div><h3>{t(String(title))}</h3><p className="muted">{t(String(body))}</p></div>)}</div></section>
      <section className="section legal" id="imprint"><h2>{t("portalNavImprint")}</h2><p>{t("portalImprintIntro")}</p><div className="card"><strong>{t("portalCompanyName")}</strong><p>{t("portalBusinessPurpose")}: {t("portalBusinessPurposeValue")}</p></div></section>
      <section className="section legal" id="privacy"><h2>{t("portalNavPrivacy")}</h2><p>{t("portalPrivacyIntro")}</p><div className="card"><h3>{t("portalPrivacyDataTitle")}</h3><p>{t("portalPrivacyDataBody")}</p><h3>{t("portalPrivacyRightsTitle")}</h3><p>{t("portalPrivacyRightsBody")}</p></div></section>
    </main>
    <footer className="footer"><div className="container footer-row"><span>© {new Date().getFullYear()} {t("portalCompanyName")}</span><div className="footer-links"><button className="button ghost" onClick={()=>scroll("imprint")}>{t("portalNavImprint")}</button><button className="button ghost" onClick={()=>scroll("privacy")}>{t("portalNavPrivacy")}</button><button className="button ghost" onClick={()=>setContactOpen(true)}>{t("portalNavContact")}</button></div></div></footer>
    {authMode&&<Modal title={authMode==="register"?t("register"):t("login")} onClose={()=>setAuthMode(null)}><AuthPanel registerMode={authMode==="register"} onBack={()=>setAuthMode(null)} onAuthenticated={()=>router.replace("/app/")}/></Modal>}
    {contactOpen&&<ContactModal onClose={()=>setContactOpen(false)}/>} 
  </div>
}

function ContactModal({onClose}:{onClose:()=>void}){const {t,locale}=useI18n();const [form,setForm]=useState({name:"",email:"",subject:"",message:"",website:""});const [state,setState]=useState<""|"busy"|"ok"|"error">("");async function submit(e:React.FormEvent){e.preventDefault();setState("busy");try{await api.sendContact({...form,locale});setState("ok")}catch{setState("error")}}return <Modal title={t("portalContactFormTitle")} onClose={onClose}><form className="form" onSubmit={submit}>{state==="ok"&&<div className="notice success">{t("portalContactSuccess")}</div>}{state==="error"&&<div className="notice error">{t("portalContactError")}</div>}<div className="field"><label>{t("name")}</label><input className="input" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>{t("email")}</label><input type="email" className="input" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div className="field"><label>{t("portalContactSubject")}</label><input className="input" required value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></div><div className="field"><label>{t("message")}</label><textarea className="textarea" required minLength={20} value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></div><input className="hidden" tabIndex={-1} autoComplete="off" value={form.website} onChange={e=>setForm({...form,website:e.target.value})}/><button className="button" disabled={state==="busy"}>{t("portalContactSend")}</button></form></Modal>}
