"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {api,ApiError} from "@/lib/api";
import {deviceContactsAvailable,selectDeviceContacts} from "@/lib/deviceContacts";
import type {CommunicationChannel,ImportDraft,Participant,ParticipantChannel,ParticipantListDetail,ParticipantListSummary} from "@/lib/types";
import {supportedLocales,useI18n} from "@/lib/i18n";
import {FileDropZone} from "../FileDropZone";
import {Modal} from "../Modal";
import {Empty,ErrorState,Loading} from "../State";

export function ListsPage({autoCreate=false,onCreateConsumed}:{autoCreate?:boolean;onCreateConsumed?:()=>void}){const {t}=useI18n();const [lists,setLists]=useState<ParticipantListSummary[]>([]);const [selected,setSelected]=useState<ParticipantListDetail|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [search,setSearch]=useState("");const [edit,setEdit]=useState<Participant|null|"new">(null);const [newList,setNewList]=useState(false);const [importOpen,setImportOpen]=useState(false);const [renameOpen,setRenameOpen]=useState(false);const [notice,setNotice]=useState("");
async function load(){setLoading(true);setError(false);try{const data=await api.lists();setLists(data);if(selected){const still=data.find(x=>x.id===selected.id);if(still)await openList(still.id);else setSelected(null)}}catch{setError(true)}finally{setLoading(false)}}
async function openList(id:string){try{setSelected(await api.list(id))}catch{setNotice(t("loadError"))}}
useEffect(()=>{void load()},[]);useEffect(()=>{if(autoCreate){setNewList(true);onCreateConsumed?.()}},[autoCreate,onCreateConsumed]);const filtered=useMemo(()=>lists.filter(l=>l.name.toLowerCase().includes(search.toLowerCase())),[lists,search]);
if(loading&&!lists.length)return <Loading/>;if(error&&!lists.length)return <ErrorState onRetry={load}/>;
return <>{notice&&<div className="notice">{notice}</div>}<div className="page-title"><div><h1>{selected?selected.name:t("participantLists")}</h1>{selected&&<button className="button ghost small" onClick={()=>setSelected(null)}>← {t("back")}</button>}</div><div className="actions">{selected?<><button className="button secondary" onClick={()=>setRenameOpen(true)}>{t("rename")}</button><button className="button secondary" onClick={()=>setImportOpen(true)}>{t("importParticipants")}</button><button className="button" onClick={()=>setEdit("new")}>{t("addParticipant")}</button></>:<button className="button" onClick={()=>setNewList(true)}>{t("newList")}</button>}</div></div>
{selected?<ListDetail list={selected} onEdit={setEdit} onReload={()=>openList(selected.id)} onNotice={setNotice}/>:<><div className="toolbar"><input className="input search" placeholder={t("searchPlaceholder")} value={search} onChange={e=>setSearch(e.target.value)}/><button className="button secondary" onClick={load}>{t("refresh")}</button></div>{filtered.length===0?<Empty text={t("noLists")}/>:<div className="table-wrap"><table className="table"><thead><tr><th>{t("name")}</th><th>{t("participants")}</th><th>{t("actions")}</th></tr></thead><tbody>{filtered.map(l=><tr key={l.id} className="clickable"><td><strong>{l.name}</strong></td><td>{l.participant_count}</td><td><button className="button secondary small" onClick={()=>openList(l.id)}>{t("view")}</button></td></tr>)}</tbody></table></div>}</>}
{newList&&<NewListModal onClose={()=>setNewList(false)} onCreated={async id=>{setNewList(false);await load();await openList(id)}}/>}{selected&&renameOpen&&<RenameListModal list={selected} onClose={()=>setRenameOpen(false)} onSaved={async()=>{setRenameOpen(false);await openList(selected.id);await load();setNotice(t("saved"))}}/>}{selected&&edit&&<ParticipantModal listId={selected.id} participant={edit==="new"?null:edit} onClose={()=>setEdit(null)} onSaved={async()=>{setEdit(null);await openList(selected.id);await load()}}/>}{selected&&importOpen&&<ImportModal listId={selected.id} onClose={()=>setImportOpen(false)} onImported={async()=>{setImportOpen(false);await openList(selected.id);await load()}}/>}</>}

function ListDetail({list,onEdit,onReload,onNotice}:{list:ParticipantListDetail;onEdit:(p:Participant)=>void;onReload:()=>void;onNotice:(v:string)=>void}){
  const {t}=useI18n();const [search,setSearch]=useState("");const filtered=list.participants.filter(p=>`${p.name} ${p.email??""} ${p.phone??""}`.toLowerCase().includes(search.toLowerCase()));
  async function remove(id:string){if(!confirm(t("deleteContactConfirm")))return;try{await api.deleteParticipant(list.id,id);onReload()}catch{onNotice(t("requestFailed"))}}
  return <><div className="toolbar"><input className="input search" placeholder={t("searchPlaceholder")} value={search} onChange={e=>setSearch(e.target.value)}/></div>{filtered.length===0?<Empty text={t("noContactsInList")}/>:<div className="table-wrap"><table className="table"><thead><tr><th>{t("name")}</th><th>{t("email")}</th><th>{t("phone")}</th><th>{t("actions")}</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><strong>{p.name}</strong></td><td>{p.email??"—"}</td><td>{p.phone??"—"}</td><td><div className="actions"><button className="button secondary small" onClick={()=>onEdit(p)}>{t("edit")}</button><button className="button ghost small danger-text" onClick={()=>remove(p.id)}>{t("delete")}</button></div></td></tr>)}</tbody></table></div>}</>}

function NewListModal({onClose,onCreated}:{onClose:()=>void;onCreated:(id:string)=>void}){const {t}=useI18n();const [name,setName]=useState("");const [busy,setBusy]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{const item=await api.createList(name);onCreated(item.id)}finally{setBusy(false)}}return <Modal title={t("newList")} onClose={onClose}><form className="form" onSubmit={submit}><div className="field"><label>{t("listName")}</label><input className="input" autoFocus value={name} onChange={e=>setName(e.target.value)}/></div><div className="actions"><button type="button" className="button secondary" onClick={onClose}>{t("cancel")}</button><button className="button" disabled={busy}>{t("create")}</button></div></form></Modal>}
function RenameListModal({list,onClose,onSaved}:{list:ParticipantListDetail;onClose:()=>void;onSaved:()=>void}){const {t}=useI18n();const [name,setName]=useState(list.name);const [busy,setBusy]=useState(false);const [error,setError]=useState("");async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await api.renameList(list.id,name.trim());onSaved()}catch{setError(t("requestFailed"))}finally{setBusy(false)}}return <Modal title={t("rename")} onClose={onClose}><form className="form" onSubmit={submit}>{error&&<div className="notice error">{error}</div>}<div className="field"><label>{t("listName")}</label><input className="input" autoFocus required value={name} onChange={e=>setName(e.target.value)}/></div><div className="actions"><button type="button" className="button secondary" onClick={onClose}>{t("cancel")}</button><button className="button" disabled={busy||!name.trim()}>{t("save")}</button></div></form></Modal>}

const contactChannels:CommunicationChannel[]=["email","whatsapp","sms","telegram"];
function channelText(t:(key:string)=>string,channel:CommunicationChannel){return channel==="whatsapp"?t("whatsApp"):t(channel)}
function channelAvailabilityText(t:(key:string)=>string,availability:ParticipantChannel["availability"]){return availability==="available"?t("channelAvailabilityAvailable"):availability==="unavailable"?t("channelAvailabilityUnavailable"):t("channelAvailabilityUnknown")}
function languageName(uiLocale:string,language:string){try{return new Intl.DisplayNames([uiLocale],{type:"language"}).of(language)??language.toUpperCase()}catch{return language.toUpperCase()}}
function draftChannelAvailability(channel:CommunicationChannel,row:ParticipantChannel|undefined,participant:Participant,email:string,phone:string,telegram:string):ParticipantChannel["availability"]{
  const current=channel==="email"?email.trim():channel==="telegram"?telegram.trim():phone.trim();
  const original=channel==="email"?(participant.email??"").trim():channel==="telegram"?(participant.channel_addresses?.telegram??"").trim():(participant.phone??"").trim();
  if(current===original)return row?.availability??(!current?"unavailable":channel==="whatsapp"?"unknown":"available");
  if(!current)return "unavailable";
  if(row?.learned)return "unknown";
  return channel==="whatsapp"?"unknown":"available";
}
function ParticipantModal({listId,participant,onClose,onSaved}:{listId:string;participant:Participant|null;onClose:()=>void;onSaved:()=>void}){
  const {t,locale}=useI18n();const [name,setName]=useState(participant?.name??"");const [email,setEmail]=useState(participant?.email??"");const [phone,setPhone]=useState(participant?.phone??"");const [telegram,setTelegram]=useState(participant?.channel_addresses?.telegram??"");const [messageLocale,setMessageLocale]=useState(participant?.locale??"");const [channels,setChannels]=useState<ParticipantChannel[]>(participant?.channels??[]);const [organizationDisabled,setOrganizationDisabled]=useState<Set<CommunicationChannel>|null>(participant?null:new Set());const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{if(!participant)return;let active=true;api.communicationSettings().then(rows=>{if(active)setOrganizationDisabled(new Set(rows.filter(row=>row.mode==="disabled").map(row=>row.channel)))}).catch(()=>{if(active)setError(t("loadError"))});return()=>{active=false}},[participant?.id,t]);
  function channelDisabled(channel:CommunicationChannel){const row=channels.find(item=>item.channel===channel);return Boolean(organizationDisabled?.has(channel)||row?.enabled===false)}
  const emailDisabled=participant?channelDisabled("email"):false;
  const phoneDisabled=participant?channelDisabled("whatsapp")&&channelDisabled("sms"):false;
  const telegramDisabled=participant?channelDisabled("telegram"):false;
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const channelAddresses:Record<string,string>=telegram.trim()?{telegram:telegram.trim()}:{};const payload={name:name.trim(),email:email.trim()||null,phone:phone.trim()||null,locale:messageLocale||null,channel_addresses:channelAddresses};try{if(participant)await api.updateParticipant(listId,participant.id,payload);else await api.addParticipant(listId,payload);onSaved()}catch(e){setError(e instanceof ApiError&&e.status===409?t("contactAlreadyExists"):t("requestFailed"))}finally{setBusy(false)}}
  async function updateChannel(channel:CommunicationChannel,enabled:boolean){if(!participant||organizationDisabled?.has(channel))return;try{const updated=await api.updateParticipantChannel(listId,participant.id,channel,{enabled});setChannels(updated.channels??[])}catch{setError(t("requestFailed"))}}
  return <Modal title={participant?t("editContact"):t("addContact")} onClose={onClose} large resizable><form className="form" onSubmit={submit}>{error&&<div className="notice error">{error}</div>}<div className="field"><label>{t("name")}</label><input className="input" required autoFocus value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label>{t("email")}</label><input type="email" className="input" value={email} disabled={emailDisabled} onChange={e=>setEmail(e.target.value)}/></div><div className="field"><label>{t("phone")}</label><input className="input" value={phone} disabled={phoneDisabled} onChange={e=>setPhone(e.target.value)}/></div><div className="field"><label>{t("participantLanguage")}</label><select className="select" value={messageLocale} onChange={e=>setMessageLocale(e.target.value)}><option value="">{t("organizationLanguageFallback")}</option>{supportedLocales.map(language=><option key={language} value={language}>{languageName(locale,language)}</option>)}</select></div><div className="field"><label>{t("telegramUsername")}</label><input className="input" value={telegram} disabled={telegramDisabled} onChange={e=>setTelegram(e.target.value)}/></div>{participant&&<details><summary>{t("contactChannels")}</summary><div className="stack"><div className="table-wrap"><table className="table channel-table"><thead><tr><th>{t("channel")}</th><th>{t("status")}</th><th>{t("disabled")}</th></tr></thead><tbody>{contactChannels.map(channel=>{const row=channels.find(item=>item.channel===channel);const availability=draftChannelAvailability(channel,row,participant,email,phone,telegram);const globallyDisabled=organizationDisabled?.has(channel)??false;const participantDisabled=row?.enabled===false;const disabled=globallyDisabled||participantDisabled;const statusText=disabled?t("disabled"):channelAvailabilityText(t,availability);const statusClass=disabled?"disabled":availability==="available"?"connected":availability==="unavailable"?"error":"";return <tr className={disabled?"channel-row-disabled":undefined} key={channel}><td><strong>{channelText(t,channel)}</strong></td><td><span className={`status-pill ${statusClass}`}>{statusText}</span></td><td><input type="checkbox" checked={disabled} disabled={organizationDisabled===null||globallyDisabled} title={globallyDisabled?`${t("communicationSettings")}: ${t("disabled")}`:undefined} aria-label={`${t("disabled")}: ${channelText(t,channel)}`} onChange={e=>void updateChannel(channel,!e.target.checked)}/></td></tr>})}</tbody></table></div></div></details>}<div className="actions"><button type="button" className="button secondary" onClick={onClose}>{t("cancel")}</button><button className="button" disabled={busy}>{t("save")}</button></div></form></Modal>
}

function ImportModal({listId,onClose,onImported}:{listId:string;onClose:()=>void;onImported:()=>void}){
  const {t}=useI18n();const [file,setFile]=useState<File|null>(null);const [rows,setRows]=useState<ImportDraft[]|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [contactsAvailable,setContactsAvailable]=useState(false);const [cameraAvailable,setCameraAvailable]=useState(false);const [stream,setStream]=useState<MediaStream|null>(null);const videoRef=useRef<HTMLVideoElement|null>(null);
  useEffect(()=>{setContactsAvailable(deviceContactsAvailable());setCameraAvailable(Boolean(navigator.mediaDevices?.getUserMedia))},[]);
  useEffect(()=>{if(videoRef.current&&stream)videoRef.current.srcObject=stream;return()=>{}},[stream]);
  useEffect(()=>()=>{stream?.getTracks().forEach(track=>track.stop())},[stream]);
  function stopCamera(){stream?.getTracks().forEach(track=>track.stop());setStream(null)}
  async function preview(nextFile=file){if(!nextFile)return;setBusy(true);setError("");try{const result=await api.previewImport(nextFile);setRows(result.participants.map(p=>({...p,selected:true})))}catch{setError(t("invalidImport"))}finally{setBusy(false)}}
  async function contacts(){setBusy(true);setError("");try{const selection=await selectDeviceContacts();if(!selection.available){setContactsAvailable(false);return}setRows(selection.contacts.map(contact=>({name:contact.name,email:contact.email,phone:contact.phone,selected:true})));setFile(null)}catch{setError(t("contactsUnavailable"))}finally{setBusy(false)}}
  async function startCamera(){setError("");try{const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});setStream(media)}catch{setError(t("cameraUnavailable"))}}
  async function capture(){const video=videoRef.current;if(!video||!video.videoWidth||!video.videoHeight)return;const canvas=document.createElement("canvas");canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext("2d")?.drawImage(video,0,0);const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/jpeg",.92));if(!blob)return;const captured=new File([blob],`camera-${Date.now()}.jpg`,{type:"image/jpeg"});setFile(captured);setRows(null);stopCamera();await preview(captured)}
  async function commit(){if(!rows)return;const selected=rows.filter(r=>r.selected).map(({selected,...rest})=>rest);if(!selected.length)return;setBusy(true);setError("");try{await api.commitImport(listId,selected);onImported()}catch(e){setError(e instanceof ApiError&&e.status===409?t("importIdentityConflict"):t("requestFailed"))}finally{setBusy(false)}}
  const allSelected=Boolean(rows?.length&&rows.every(row=>row.selected));const selectedCount=rows?.filter(row=>row.selected).length??0;
  const hasAlternativeSource=contactsAvailable||cameraAvailable;
  return <Modal title={t("importParticipants")} onClose={()=>{stopCamera();onClose()}} wide><div className="form">{error&&<div className="notice error">{error}</div>}<div className="import-source-actions"><FileDropZone accept=".pdf,.xlsx,.xlsm,.csv,.tsv,.txt,image/*" disabled={busy} file={file} hint={`${t("fileDropHint")} ${t("fileFormats")}`} dropLabel={t("fileDropChoose")} selectLabel={t("fileDropReplace")} onFile={next=>{setFile(next);setRows(null);setError("")}}/>{hasAlternativeSource&&<><div className="import-source-divider"><span>{t("importAlternative")}</span></div><div className="actions import-source-buttons">{cameraAvailable&&<button type="button" className="button secondary" onClick={startCamera} disabled={busy||Boolean(stream)}>{t("takePhoto")}</button>}{contactsAvailable&&<button type="button" className="button secondary" onClick={contacts} disabled={busy}>{t("importFromContacts")}</button>}</div></>}</div>{stream&&<div className="camera-capture"><video ref={videoRef} autoPlay playsInline muted/><div className="actions"><button type="button" className="button" onClick={capture}>{t("usePhoto")}</button><button type="button" className="button secondary" onClick={stopCamera}>{t("cancel")}</button></div></div>}{!rows&&<button className="button" onClick={()=>preview()} disabled={!file||busy}>{t("preview")}</button>}{rows&&<><div className="row between"><strong>{t("recognizedParticipants",{count:rows.length})}</strong><button type="button" className="button ghost small" onClick={()=>setRows(rows.map(row=>({...row,selected:!allSelected})))}>{allSelected?t("deselectAll"):t("selectAll")}</button></div><div className="table-wrap"><table className="table"><thead><tr><th></th><th>{t("name")}</th><th>{t("email")}</th><th>{t("phone")}</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${r.name}-${i}`}><td><input type="checkbox" checked={!!r.selected} onChange={e=>setRows(rows.map((x,j)=>j===i?{...x,selected:e.target.checked}:x))}/></td><td>{r.name}</td><td>{r.email??"—"}</td><td>{r.phone??"—"}</td></tr>)}</tbody></table></div><button className="button" onClick={commit} disabled={busy||selectedCount===0}>{t("importSelected",{count:selectedCount})}</button></>}</div></Modal>
}
